-- CreateTable
CREATE TABLE "KillEvent" (
    "id" TEXT NOT NULL,
    "eventId" BIGINT NOT NULL,
    "battleId" BIGINT,
    "timestamp" TIMESTAMP(3) NOT NULL,
    "killArea" TEXT,
    "groupMemberCount" INTEGER NOT NULL,
    "killerId" TEXT NOT NULL,
    "killerName" TEXT NOT NULL,
    "killerGuildId" TEXT,
    "killerGuildName" TEXT,
    "killerAllianceId" TEXT,
    "killerAllianceName" TEXT,
    "killerAllianceTag" TEXT,
    "killerAvgIP" INTEGER NOT NULL,
    "killerDeathFame" BIGINT,
    "killerKillFame" BIGINT,
    "killerFameRatio" DOUBLE PRECISION,
    "killerMostUsedWeaponPicture" TEXT,
    "killerEquipment" JSONB NOT NULL,
    "victimId" TEXT NOT NULL,
    "victimName" TEXT NOT NULL,
    "victimGuildId" TEXT,
    "victimGuildName" TEXT,
    "victimAllianceId" TEXT,
    "victimAllianceName" TEXT,
    "victimAllianceTag" TEXT,
    "victimAvgIP" INTEGER NOT NULL,
    "victimDeathFame" BIGINT,
    "victimKillFame" BIGINT,
    "victimFameRatio" DOUBLE PRECISION,
    "victimMostUsedWeaponPicture" TEXT,
    "victimEquipment" JSONB NOT NULL,
    "groupMembers" JSONB,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "KillEvent_pkey" PRIMARY KEY ("id")
);
